image: docker:19.03.13

services:
    - docker:dind

stages:
  - build
  - test
  - push

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  only:
    changes:
      - src/*
      - tests/*
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --pull --build-arg VCS_REF=$CI_COMMIT_SHA --build-arg VCS_URL=$CI_PROJECT_URL --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA

test:
  stage: test
  only:
    changes:
      - src/*
      - tests/*
  script:
    - docker pull $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA
    - docker run $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA poetry run python -m unittest -v tests/test_main.py
    # - docker run $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA poetry run python -m unittest -v tests/test_pods.py
    - docker run $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA poetry run python -m unittest -v tests/test_route.py
    # - docker run $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA poetry run python -m unittest -v tests/test_routing.py

push_tag:
  stage: push
  variables:
    GIT_STRATEGY: none
  only:
    - tags
  script:
    - docker pull $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

push_latest:
  stage: push
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - main
    changes:
      - src/*
      - tests/*
  script:
    - docker pull $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:build_$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest