apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: netroutes.dev.nitsche.io
spec:
  group: dev.nitsche.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        properties:
          spec:
            type: object
            properties:
              destination:
                type: string
              gateway:
                type: string
              targetPod:
                type: string
              targetNamespace:
                type: string
    additionalPrinterColumns:
        - name: READY
          type: string
          priority: 0
          jsonPath: .status.netroute_creation_handler.ready
          description: Readiness status of NetRoute
        - name: ROUTE
          type: string
          priority: 0
          jsonPath: .status.netroute_creation_handler.route
          description: The Network Route in CIDR Notation
        - name: APPLIED TO
          type: string
          priority: 0
          jsonPath: .status.netroute_creation_handler.applied_to
          description: The NS + Pod on which the Route was created
        - name: AGE
          type: date
          priority: 0
          jsonPath: .metadata.creationTimestamp
          description: Age of the NetRoute
  scope: Namespaced
  names:
    plural: netroutes
    singular: netroute
    kind: NetRoute
