# A demo CRD for the Kopf example operators.
# Use it with Kubernetes 1.16 and above.
# For Kubernetes 1.15 and below, use crd-v1beta1.yaml.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: netroutes.samy.nitsche.io
spec:
  scope: Namespaced
  group: samy.nitsche.io
  names:
    kind: NetRoute
    plural: netroutes
    singular: netroute
    shortNames:
      - netroute
      - netroutes
      - nr
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: READY
          type: string
          priority: 0
          jsonPath: .status.create_route.ready
          description: Readiness status of NetRoute
        - name: ROUTE
          type: string
          priority: 0
          jsonPath: .status.create_route.route
          description: The Network Route in CIDR Notation
        - name: APPLIED TO
          type: string
          priority: 0
          jsonPath: .status.create_route.applied_to
          description: The NS + Pod on which the Route was created
        - name: AGE
          type: date
          priority: 0
          jsonPath: .metadata.creationTimestamp
          description: Age of the NetRoute