---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ["sh", "-c", "tail -f /dev/null"]
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2-test
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ["sh", "-c", "tail -f /dev/null"]
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox3-test
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ["sh", "-c", "tail -f /dev/null"]
    securityContext:
      capabilities:
        add:
          - NET_ADMIN