name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install Plugins
        run: npm install @semantic-release/github @semantic-release/changelog @google/semantic-release-replace-plugin @semantic-release/git -D
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_KEY }}
        run: npx semantic-release